# Generated by Django 3.1.7 on 2021-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20210304_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
