# Generated by Django 3.1.7 on 2021-03-08 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0009_content_author_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(related_name='liked_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
