# Generated by Django 3.1.7 on 2021-04-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20210308_0234'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author_username'], name='contents_co_author__e2da0e_idx'),
        ),
    ]
