# Generated by Django 3.1.7 on 2021-03-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_username',
            field=models.CharField(default='Anonymous', max_length=63),
        ),
    ]
