# Generated by Django 3.1.7 on 2021-02-28 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(default=0, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
