# Generated by Django 3.1.7 on 2021-02-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
