# Generated by Django 3.1.7 on 2021-03-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20210308_0234'),
        ('notifications', '0002_auto_20210311_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.content'),
        ),
    ]
